In [1]:
import pandas as pd
import re
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
atus_sum = pd.read_csv("/Users/travisknop/travis_python/homework/adventure-time/adventure_time/atus_data/atussum_2014.dat")

print(atus_sum[0])

KeyError: 0

In [6]:
atus_sum.rename(columns={'tucaseid':'PersonID', 'TUFINLWGT':'Weight', 'TRYHHCHILD':'Youngest_child', 'TEAGE':'Age', 'TESEX':'Sex', 'PEEDUCA':'Education', 'PTDTRACE':'Race', 'GTMETSTA':'Metro_status', 'TELFS':'Labor_status', 'TRERNWA':'Wkly_earnings'}, inplace=True)
atus_sum

,PersonID,Weight,Youngest_child,Age,Sex,Education,Race,PEHSPNON,Metro_status,Labor_status,...,t181601,t181699,t181801,t181899,t189999,t500101,t500103,t500105,t500106,t500107
0,20140101140007,4891315.826760,0,20,2,39,1,1,1,4,...,0,0,0,0,0,0,0,0,0,0
1,20140101140011,23147368.359655,16,16,2,37,2,2,1,1,...,0,0,0,0,0,0,0,0,0,0
2,20140101140028,20941823.429044,2,65,2,38,1,1,1,5,...,0,0,0,0,0,0,0,0,0,0
3,20140101140063,2505899.417166,-1,50,2,39,2,2,2,5,...,0,0,0,0,0,0,0,0,0,0
4,20140101140168,15928231.823165,8,23,2,39,2,2,2,4,...,0,0,0,0,0,0,0,0,0,0
5,20140101140537,3622350.817628,-1,85,1,36,2,2,1,5,...,0,0,0,0,0,0,0,0,0,0
6,20140101140559,3653337.861341,1,27,1,43,1,2,2,1,...,0,0,0,0,0,0,0,0,0,0
7,20140101140610,11589604.860274,0,28,1,42,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
8,20140101140614,2019096.316437,-1,63,2,40,1,2,1,1,...,0,0,0,0,0,0,0,0,70,0
9,20140101140639,5332005.152751,-1,85,1,44,1,2,1,5,...,0,0,0,0,0,0,0,0,0,0
10,20140101140665,4778595.528829,-1,66,2,39,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
11,20140101140685,7015085.157922,-1,54,1,39,1,2,1,5,...,0,0,0,0,0,0,0,0,0,0
12,20140101140702,6323639.241364,0,31,2,39,1,1,1,5,...,0,0,0,0,0,0,0,0,0,0
13,20140101140725,7339555.320589,1,35,1,44,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
14,20140101140759,19564172.363871,-1,80,1,34,1,2,1,5,...,0,0,0,0,0,0,0,0,0,0
15,20140101140792,17110667.548441,-1,37,1,40,8,2,1,3,...,0,0,0,0,0,45,0,0,0,0
16,20140101140804,6209017.526033,10,41,2,42,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
17,20140101140836,2068191.833256,-1,85,2,34,1,2,1,5,...,0,0,0,0,0,0,0,0,0,0
18,20140101140852,2182116.985390,-1,67,1,43,1,2,1,5,...,0,0,0,0,0,0,0,0,0,0
19,20140101140854,4731635.020056,-1,21,2,40,1,1,1,5,...,0,0,0,0,0,0,0,0,0,0
20,20140101140872,8369759.181566,9,45,2,40,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
21,20140101140875,11463166.416109,-1,62,1,43,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
22,20140101140876,4376665.609382,-1,67,2,39,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
23,20140101140885,4659170.172209,-1,80,2,41,1,2,1,5,...,0,0,0,0,0,0,0,0,0,0
24,20140101140911,10415633.647422,-1,61,2,40,1,2,1,5,...,0,0,0,0,0,0,0,0,0,0
25,20140101140940,3624692.126833,14,49,1,39,1,2,1,5,...,0,0,0,0,0,0,0,0,0,0
26,20140101140958,9199818.278835,0,26,2,39,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
27,20140101140967,3840512.602825,-1,66,2,43,1,2,1,5,...,0,0,0,0,0,0,0,0,0,0
28,20140101140973,12684691.638659,-1,62,1,40,5,2,1,1,...,0,0,0,0,0,0,0,0,0,0
29,20140101140990,5305349.062981,-1,61,1,43,1,2,1,5,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11562,20141212142154,5410085.933352,-1,69,2,36,1,1,1,5,...,0,0,0,0,0,0,0,0,0,0
11563,20141212142164,14707247.050177,-1,55,2,39,1,1,1,5,...,0,0,0,0,0,0,0,0,0,0
11564,20141212142168,3768521.046107,14,17,2,36,1,2,1,5,...,0,0,0,0,0,0,0,0,0,0
11565,20141212142172,2305855.345249,3,32,2,43,1,2,1,2,...,0,0,0,0,0,0,0,0,0,0
11566,20141212142199,14809761.200252,-1,57,2,39,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
11567,20141212142201,16109771.908348,-1,60,1,43,1,2,2,1,...,0,0,0,0,0,0,0,0,0,0
11568,20141212142204,9854368.080553,-1,66,2,44,2,2,2,5,...,0,0,0,0,0,0,0,0,0,0
11569,20141212142215,28463790.753911,-1,26,1,43,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
11570,20141212142236,3627508.387620,5,33,1,39,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
11571,20141212142238,10053654.033256,11,43,1,43,1,2,1,1,...,0,0,0,0,20,30,0,0,0,0
11572,20141212142263,1580562.670392,-1,45,1,43,2,2,1,1,...,0,0,0,0,0,0,0,0,0,0
11573,20141212142273,4062957.914849,6,17,1,37,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
11574,20141212142288,8890237.936590,-1,31,2,43,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
11575,20141212142311,5993183.760352,-1,74,2,39,1,2,2,5,...,0,0,0,0,0,0,0,0,0,0
11576,20141212142318,10823445.226531,-1,28,1,43,8,2,1,1,...,0,0,0,0,0,0,0,0,0,0
11577,20141212142361,1418186.763175,4,25,2,40,1,2,2,1,...,0,0,0,0,0,0,0,0,0,0
11578,20141212142393,28379174.037286,6,48,1,39,1,1,1,5,...,0,0,0,0,0,0,0,0,0,0
11579,20141212142397,12406838.728274,-1,18,1,38,2,2,1,5,...,0,0,0,0,0,0,0,0,0,0
11580,20141212142398,38528913.078285,-1,52,1,34,4,2,1,1,...,0,0,0,0,0,0,0,0,0,0
11581,20141212142400,9217117.947516,-1,79,1,34,1,1,1,5,...,0,0,0,0,0,0,0,0,0,0
11582,20141212142422,15522995.508440,-1,65,1,43,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
11583,20141212142441,5664041.151625,-1,70,1,42,1,2,2,1,...,0,0,0,0,0,0,0,0,0,0
11584,20141212142461,2000632.462062,-1,75,1,39,1,1,1,5,...,0,0,0,0,0,0,0,0,0,0
11585,20141212142462,8271422.232486,1,33,2,43,1,2,1,1,...,5,0,0,0,0,75,0,0,0,0
11586,20141212142470,1597584.375957,15,37,2,42,1,2,1,4,...,0,0,0,0,0,0,0,0,0,0
11587,20141212142472,10307159.601924,-1,28,1,40,1,2,1,2,...,0,0,0,0,0,0,0,0,0,0
11588,20141212142476,12385683.762434,-1,57,1,42,4,2,1,1,...,0,0,0,0,0,0,0,0,0,0
11589,20141212142480,7601986.249457,16,57,2,43,4,2,1,5,...,0,0,0,0,0,0,0,0,0,0
11590,20141212142484,10999877.751824,12,23,1,40,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
11591,20141212142500,2319771.253360,3,30,2,43,1,2,1,5,...,0,0,0,0,0,0,0,0,0,0